parameters:
#    rj_admin.example.class: RJ\AdminBundle\Example

services:
#    rj_admin.example:
#        class: %rj_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
