parameters:
#    rj_user.example.class: RJ\UserBundle\Example

services:
    rj_user.registration.form.type:
        class: RJ\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: rj_user_registration }
