parameters:
#    rj_utilities.example.class: RJ\UtilitiesBundle\Example

services:
#    rj_utilities.example:
#        class: %rj_utilities.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
